### ISSUE TITLE
Limit parameter

### ISSUE THREAD

**Issue by Nessus85100** [BigNoid/service.library.data.provider#25]
At the moment the "limit=" parameter works only if you want to decrease the items number lower then 20. Is it possible to use the limit parameter to increase the number of items to more then 20 ?

Cheers
Nessus

**Comment by Nessus85100** [comment]
bump ?

**Comment by BigNoid** [comment]
Thats because the overriding setting is set to fetch a maximum of 20 items in the database. If you increase that setting the limit parameter will work also with larger numbers.

**Comment by Nessus85100** [comment]
I use this to increase the limit to 50 items...

    <content>plugin://service.library.data.provider?type=randommovies&amp;limit=50&amp;reload=$INFO[Window(Home).Property(randommovies)]</content>
...but i am still getting 20 items in the list. Is the above code wrong ?

Cheers
Nessus

**Comment by BigNoid** [comment]
I mean [this] (https://github.com/BigNoid/service.library.data.provider/blob/master/resources/settings.xml#L5) setting. That is accesible through the addon settings page and overrides any limit parameter in terms of max fetched items.

**Comment by Nessus85100** [comment]
I know about that but that requires user interaction. I want to fill a list with more than 20 items without any user interaction. Is that not possible through a parameter in the content tag ?

**Comment by BigNoid** [comment]
I wanted to have full control for the end user, since this parameter greatly affects loading speed of the list. You are probably right; adding the parameter should override it to allow more flexibility for the skinner. Only disadvantage is that it renders the addon setting useless.

**Comment by Nessus85100** [comment]
So, not possible ?

**Comment by Nessus85100** [comment]
I guess not.
