### ISSUE TITLE
feature request: sort recommended episodes on date

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/service.library.data.provider#26]
Hi,

Just a little feature request for whenever you have time for this:
Is it possible to sort the "recommended episodes" on date ? So, the episode of the last watched TV show first ?

If you want I can take a look myself and send you a MR ?

Regards,

Marcel

**Comment by BigNoid** [comment]
It should already do that (and does on my end):
- https://github.com/BigNoid/service.library.data.provider/blob/master/library.py#L233
- https://github.com/BigNoid/service.library.data.provider/blob/master/library.py#L240

**Comment by marcelveldt** [comment]
Oh damn, you're abolutely right, it does indeed ;-)

Also confirmed by a happy user:
http://forum.kodi.tv/showthread.php?tid=201061&pid=1925144#pid1925144

Thanks!
