### ISSUE TITLE
ListItem.Type / ListItem.Property(Type)

### ISSUE THREAD

**Issue by bkury** [BigNoid/service.library.data.provider#33]
Hello,

First I want to thank you for your work on this script. One "issue" I have is the missing ListItem.Type infolabel for dynamic <content> lists.

e.g. one example would be.:
When using the "recentvideos" content list, it would be nice to have different images (Poster or Thumb)  based on content (Movie or Episode) but this can only be done if I can distinguish based on  ListItem.Type(movie/episode).

There are more situations where this could be really helpful, so for the sake of completeness it would be nice to have this infolabel available.

thanks again!

**Comment by bkury** [comment]
Forget it, I just realized that ListItem.Property(type) gets populated, not with what I expected but it's good enough to use SubString() on that infolabel ....

thanks anyway!

**Comment by MartijnKaijser** [comment]
without looking in the code, is http://mirrors.xbmc.org/docs/python-docs/14.x-helix/xbmcplugin.html#-setContent used for setting correct content?

**Comment by BigNoid** [comment]
Yep thats being set correctly, see https://github.com/BigNoid/service.library.data.provider/blob/master/default.py#L57. Only works in plugin mode ofc and not in widgets on home screen (as this is not a media window).

**Comment by bkury** [comment]
Yes, you are right .. I was working with some outdated code, now everything is fine!

Anyway, thanks for your help and time!
