### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by MartijnKaijser** [BigNoid/service.library.data.provider#40]
remove xbmc.addon
update xbmc.python to 2.14.0

**Comment by BigNoid** [comment]
Completely missed this one :/
Why does xbmc.addon needs to be removed?

**Comment by MartijnKaijser** [comment]
it should have never been addon as xbmc.addon doesn't give functionality

**Comment by BigNoid** [comment]
Okay thx. Will remove it.
